name: Provision EC2 and Configure Monitoring Tools

on:
  push:
    branches:
      - main

jobs:
  provision:
    name: Provision EC2 and Setup Monitoring
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
        cli_config_credentials_token: ${{ secrets.AWS_ACCESS_KEY_ID }}

    - name: Initialize Terraform
      run: |
          terraform init
          terraform apply -auto-approve
          terraform output -json > output.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Get EC2 Public IP
      id: ec2-ip
      run: |
        echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

    - name: Configure SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Install Ansible
      run: sudo apt update && sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible-playbook.yml \
          --inventory "ec2-user@${{ steps.ec2-ip.outputs.public_ip }}," \
          --key-file ~/.ssh/id_rsa
