name: Provision EC2 and Configure Monitoring Tools

on:
  push:
    branches:
      - main

jobs:
  provision:
    name: Provision EC2 and Setup Monitoring
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
        cli_config_credentials_token: ${{ secrets.AWS_ACCESS_KEY_ID }}

    - name: Initialize Terraform and Get Public IP
      id: terraform
      run: |
        terraform init
        terraform apply -auto-approve
        PUBLIC_IP=$(terraform output -json | jq -r '.public_ip.value')
        echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Configure SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Install Ansible
      run: sudo apt update && sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook ansible-playbook.yml \
          --inventory "ec2-user@${{ env.PUBLIC_IP }}," \
          --key-file ~/.ssh/id_rsa
